import React, { useEffect, useState } from "react";
import UpdateGrid from "../components/updateGrid";
import Head from "next/head";
import {
  session,
  ENVIRONMENT,
  setClientenvsInSession,
  CLIENT_ENVIRONMENT,
  CONSTANTS,
} from "../lib/util";
import ViewSelector from "../components/views/ViewSelector";
import CurrentMatch from "../components/views/CurrentMatch/CurrentMatch";
import useDashboard from "../hooks/useDashboard";
import { useRouter } from "next/router";
import { axiosClient } from "../lib/apiClient";

export default function Admin({
  initalTeamsData,
  initalDashboard,
  leagues,
  clientenvs,
  views,
}) {
  const defaultLeague = leagues?.filter((l) => l.default)[0];
  const [league, setLeague] = useState(defaultLeague);
  const { view, teams, currentMatch, updateView } = useDashboard({
    initalDashboard,
    clientenvs,
    league,
    initalTeamsData,
  });
  const router = useRouter();

  return (
    <div className="container-fluid">
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-100">
        <h1 className="my-3">Admin Panel</h1>
        <div className="d-flex">
          <label htmlFor="league-selector" className="mx-2">
            League:
          </label>
          <select
            id="league-selector"
            aria-label="Default select example"
            onChange={(e) => {
              setLeague(leagues.find((l) => l._id === e.target.value));
            }}
            value={league["_id"]}
          >
            {leagues.map((l) => (
              <option key={l._id} value={l._id}>
                {l.name}
              </option>
            ))}
          </select>
        </div>

        <UpdateGrid data={teams} league={league} />
        <div className="row justify-content-md-center">
          <div className="col-md-8 col-12  dev">
            <ViewSelector
              views={views}
              initlaView={view}
              onViewSelectorChnage={updateView}
            />
          </div>
          <div className="col-md-4 col-12 dev">
            <h3 className="text-center">Current Preview</h3>
            <div className="m-1">
              <CurrentMatch
                match={currentMatch}
                matchView={view}
                miniView={true}
              />
              <button
                hidden={view === CONSTANTS.VIEWS.STANDINGS}
                className="btn btn-outline-warning btn-block w-100"
                onClick={() => router.push(`matches`)}
              >
                Update
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const envs = CLIENT_ENVIRONMENT;
  const axios = axiosClient(context.req);
  try {
    const teamsResponse = await axios.get(`api/teams`);
    const leaguesResponse = await axios.get(`api/leagues`);
    const dashboardResponse = await axios.get(`api/dashboard`);
    const viewsResponse = await axios.get(`api/views`);
    const initalTeamsData = await teamsResponse["data"];
    const leagues = await leaguesResponse["data"];
    const initalDashboardData = await dashboardResponse["data"];
    const ViewsData = await viewsResponse["data"];
    // Pass data to the page via props
    return {
      props: {
        initalDashboard: initalDashboardData["data"],
        initalTeamsData: initalTeamsData["data"],
        leagues: leagues["data"],
        clientenvs: envs,
        views: ViewsData["data"],
      },
    };
  } catch (err) {
    return {
      redirect: {
        destination: "/auth/signin",
        permanent: false,
      },
    };
  }
}
