import React, { useEffect, useState } from "react";
import UpdateGrid from "../components/updateGrid";
import Head from "next/head";
import { session, ENVIRONMENT } from "../lib/util";

export default function Admin({ initalTeamsData, league }) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [passcode, setPasscode] = useState("");
  useEffect(() => {
    session.set("passcode", passcode);
    if (
      session.get("passcode") &&
      session.get("passcode") === ENVIRONMENT.AdminPasscode
    ) {
      setIsLoggedIn(true);
      return;
    }
    setIsLoggedIn(false);
  }, [passcode]);
  if (!isLoggedIn) {
    return (
      <div className="container">
        <label>Enter the passcode</label>
        <div className="w-25">
          <input
            className="w-100"
            type="password"
            value={passcode}
            onChange={(e) => setPasscode(e.target.value)}
          />
        </div>
      </div>
    );
  }
  return (
    <div className="container-fluid">
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="my-3">Admin Panel</h1>
      <UpdateGrid data={initalTeamsData.data} league={league} />
    </div>
  );
}

export async function getServerSideProps() {
  const teamsResponse = await fetch(`${ENVIRONMENT.BaseApiURL}/teams`);
  const leagueResponse = await fetch(`${ENVIRONMENT.BaseApiURL}/league`);
  const initalTeamsData = await teamsResponse.json();
  const leagues = await leagueResponse.json();
  // Pass data to the page via props
  return { props: { initalTeamsData, league: leagues["data"][0] } };
}
