import Head from "next/head";
import Image from "next/image";
import Table from "../components/table";
import { ENVIRONMENT, setClientenvsInSession } from "../lib/util";
import styles from "../styles/Home.module.css";

export default function Home({ initalTeamsData, league }) {
  // add envs to session
  setClientenvsInSession(clientenvs);
  return (
    <div className={styles.container}>
      <Head>
        <title>{league["name"]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container-fluid mt-2">
        <div className="d-flex justify-content-center my-5">
          <h1>{league["name"]}</h1>
        </div>
        <Table data={initalTeamsData.data} />
      </main>
      {/* 
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created By{" "}
          <span className={styles.logo}>
            <Image
              src="/melkorCba-react.png"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer> */}
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const envs = CLIENT_ENVIRONMENT;

  const teamsResponse = await fetch(`${ENVIRONMENT.BaseApiURL}/teams`);
  const leagueResponse = await fetch(`${ENVIRONMENT.BaseApiURL}/league`);
  const initalTeamsData = await teamsResponse.json();
  const leagues = await leagueResponse.json();
  // Pass data to the page via props
  return {
    props: {
      initalTeamsData,
      league: leagues["data"][0],
      clientenvs: envs,
    },
  };
}
