name: "Create Standing App Release"
on:
  release:
    types: [created]

env:
  VERSION: ${{ github.event.release.tag_name }}
  BASE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/standings-board
  IMAGE_TAG:

jobs:
  set_version_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to release branch
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Set release tag
        run: echo "VERSION=${{github.event.release.tag_name}}" >> $GITHUB_ENV
      - run: echo "${{env.VERSION}}"

      - name: Set image tag
        run: echo "IMAGE_TAG=${{env.BASE_TAG}}:${{env.VERSION}}" >> $GITHUB_ENV
      - run: echo "${{env.IMAGE_TAG}}"

  build:
    needs: set_version_info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to release tag
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image artifact
        id: build-image-artifact
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.IMAGE_TAG}}
          outputs: type=docker,dest=/tmp/${{ env.IMAGE_TAG}}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build-image-artifact.outputs.metadata }}
          path: /tmp/${{ env.IMAGE_TAG }}.tar
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG}}
