name: "Release Standing App"
on:
  workflow_dispatch:

env:
  VERSION: "latest"

jobs:
  set_version:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version as environment variable
        run: echo "export VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
        shell: bash
  print_version:
    needs: set_version
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: echo "The version is $VERSION"
