name: "Create Standing App Release"
on:
  release:
    types: [created]

env:
  VERSION: ${{ github.event.release.tag_name }}
  IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/standings-board:${{github.event.release.tag_name}}

jobs:
  version_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to release branch
        uses: actions/checkout@v2
        with:
          ref: release

      - name: release tag
        run: echo "${{env.VERSION}}"

      - name: new image tag
        run: echo "${{env.IMAGE_TAG}}"

  build:
    needs: version_info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to release tag
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG}}
